In [3]:
import random
import numpy as np
import time

# python原生list
a = list()
for i in range(100000):
    a.append(random.random())

%time sum1 = sum(a)

a = list()

for i in range(100000):
    a.append(random.random())
b = np.array(a)
%time sum2 = np.sum(b)


CPU times: total: 0 ns
Wall time: 1 ms
CPU times: total: 0 ns
Wall time: 0 ns


In [3]:
import numpy as np

a = np.array([[0, 1, 2, 3 ,4],
             [5, 6, 7, 8, 9]])
print(a.ndim)

print(a.shape)

print(a.size)

print(a.dtype)

print(a.itemsize)

2
(2, 5)
10
int32
4


In [9]:
arr = np.arange(3, 9)
print(arr)

arr = np.ones((2, 6))
print(arr)


[3 4 5 6 7 8]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [33]:
# 最小维度
import numpy as np
a = np.array([1, 2, 3.14, 4, 5], ndmin=2, dtype=complex)
# print(a)


# d = np.ones((2, 3, 4), dtype=int)

# print(d)

d = np.arange(24).reshape(2, 3, 4)

# print(d)
print()
print(d[1: 2: 1])


[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [35]:
import numpy as np 
 
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：')
print (x)
print ('\n')
# 现在我们会打印出大于 5 的元素  
print  ('大于 5 的元素是：')
print (x[x >=  5])

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


大于 5 的元素是：
[ 5  6  7  8  9 10 11]


# 数组创建

In [10]:
import numpy as np
zero = np.zeros(5)
print(zero)

two = np.zeros([5, 6])
print(two)


one = np.ones([2, 3], dtype = 'int32')
print(one)

# 创建一个 3x3 的二维数组
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 
# 创建一个与 arr 形状相同的，所有元素都为 1 的数组
ones_arr = np.ones_like(arr)
print(ones_arr)


# numpy.empty 方法用来创建一个指定形状（shape）、数据类型（dtype）且未初始化的数组：
x = np.empty([3,2], dtype = int) 
print (x)




[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


# 浅拷贝和深拷贝

In [17]:
two = np.zeros([5,6])
print(two)

# 深拷贝
a = np.array(two)

a[0][0] = 3

print(two)



# 浅拷贝
b = np.asarray(two)

b[0][0] = 1

print(two)



[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# 广播机制

In [1]:
# 广播的规则:
# ①让所有输入数组都向其中形状最长的数组看齐，形状中不足的部分都通过在前面加 1 补齐。
# ②输出数组的形状是输入数组形状的各个维度上的最大值。
# ③如果输入数组的某个维度和输出数组的对应维度的长度相同或者其长度为 1 时，这个数组能够用来计算，否则出错。
# ④当输入数组的某个维度的长度为 1 时，沿着此维度运算时都用此维度上的第一组值。

import numpy as np

a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])

# ①
b = np.array([1,2,3])
c = a + b
print(c)

# ②




[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


# 实验4：切片和索引

In [35]:
import numpy as np
 
# # ndarray 数组可以基于 0 - n 的下标进行索引，切片对象可以通过内置的 slice 函数，并
# # 设置 start, stop 及 step 参数进行，从原数组中切割出一个新数组。    
# a = np.arange(10)
# s = slice(3,8,2)   # 从索引 3 开始到索引 8 停止，间隔为2
# print(s) #返回索引存储在tuple中 
# print (a[s])# [3, 5, 7]



#冒号分隔切片参数 start:stop:step 来进行切片操作：
# a = np.arange(15)  
# b = a[2:13:2]   # 从索引 2 开始到索引 13 停止，间隔为 2
# print(b) # [2, 4 ,6，8， 10，12]

# #索引访问
# a = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]
# b = a[5] 
# print(b) # 5


#多维数组切片
# print('\n')
# a = np.array([[1,2,3,4],[3,4,5, 6],[4,5,6, 7]])
# print(a)

# # 从某个索引处开始切割
# print('\n')
# print('从数组索引 a[1:] 处开始切割') # 列和行数 = 索引数 + 1
# print(a[1::, 1:3:]) # 因为此处的为二维对象，因此前面的 '1::'表示行的切片，从第二行开始， '1:3:'表示为
#                     #列从第二列开始，切割到第四列，不包括第四列，表示包括第二列和第三列


#切片还可以包括省略号 …，来使选择元组的长度与数组的
#维度相同。 如果在行位置使用省略号，它将返回包含行中元素的 ndarray。
# a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
# print(a)
# print("")
# print (a[...,1])   # 第2列元素
# print (a[1,...])   # 第2行元素
# print (a[...,1:])  # 第2列及剩下的所有元素




#高级索引：
'''
NumPy 比一般的 Python 序列提供更多的索引方式。
除了之前看到的用整数和切片的索引外，数组可以由整数数组索引、布尔索引及花式索引。
NumPy 中的高级索引指的是使用整数数组、布尔数组或者其他序列来访问数组的元素。相比
于基本索引，高级索引可以访问到数组中的任意元素，并且可以用来对数组进行复杂的操作和修改。
'''
#①整数数组索引

# a = np.arange(20).reshape(4, 5)
# print(a)
# print("")

# y = a[[0, 3, 2], [2, 3, 1]] #此次的数组可理解为，前面的[0, 3, 2]为x轴坐标，[2, 3, 1]为y轴坐标
#                             #然后一一对应从x和y中取出坐标，等价于a[0, 2], a[3, 3], a[2, 1]
# print(y) #结果为[2 18 11]
# print(a[0, 2], a[3, 3], a[2, 1])

#②布尔索引
# 可以通过一个布尔数组来索引目标数组。
#布尔索引通过布尔运算（如：比较运算符）来获取符合指定条件的元素的数组。
#如下获得所有大于8的元素
# a = np.arange(20).reshape(4, 5)
# print("")
# b = a[a > 8]
# print("所有大于8的元素为：")
# print(b)

# ax = np.array([1, 3 + 4j, 8 + -2j, 7])
# print("获取所有复数的元素：")
# res = ax[np.iscomplex(ax)]
# print(res)

#③花式索引：
# 花式索引指的是利用整数数组进行索引。
# 花式索引根据索引数组的值作为目标数组的某个轴的下标来取值。
# 对于使用一维整型数组作为索引，如果目标是一维数组，那么索引的结果就是
# 对应位置的元素， 如果目标是二维数组，那么就是对应下标的行。
# 花式索引跟切片不一样，它总是将数据复制到新数组中。

# 3.1一维数组：一维数组只有一个轴 axis = 0，所以一维数组就在 axis = 0 这个轴上取值：
# x = np.arange(9)
# print(x)
# # 一维数组读取指定下标对应的元素
# print("-------读取下标对应的元素-------")
# x2 = x[[0, 6]] # 使用花式索引
# print(x2)

# print(x2[0])
# print(x2[1])

#3.2二维数组：
# 3.2.1、传入顺序索引数组
# x=np.arange(56).reshape((8,7))
# print(x)
# # 二维数组读取指定下标对应的行
# print("-------读取下标对应的行-------")
# print (x[[4,2,1,7]]) #输出索引为4， 2， 1， 7所对应的行

# # 3.2.2传入倒序索引数组
# print("倒叙索引：")
# print (x[[-4,-2,-1,-7]])

# 3.3传入多个索引数组（要使用 np.ix_）
# np.ix_ 函数就是输入两个数组，产生笛卡尔积的映射关系。
# 笛卡尔乘积是指在数学中，两个集合 X 和 Y 的笛卡尔积（Cartesian product），
# 又称直积，表示为 X×Y，第一个对象是X的成员而第二个对象是 Y 的所有可能有序对的其中一个成员。
x=np.arange(32).reshape((8,4))
print(x)
print("\n")
print (x[np.ix_([1,5,7,2],[0,3,1,2])]) 
#求笛卡儿积：即按照笛卡尔积求得索引，然后获取如： x[1][0]，x[1, 3], x[1, 1], [1, 2]
#简单理解

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


# 六.数据访问与修改

In [8]:
import numpy as np
 
    
 #append()   
a = np.array([[1,2,3],[4,5,6]])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('向数组添加元素：')
print (np.append(a, [7,8,9]))
print ('\n')
 
print ('沿轴 0 添加元素：')
print (np.append(a, [[7,8,9]],axis = 0))
print ('\n')
 
print ('沿轴 1 添加元素：')
print (np.append(a, [[5,5,5],[7,8,9]],axis = 1))

#vstack(),上下拼接
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：')
print (a)
print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：')
print (b)
print ('\n')
 
print ('竖直堆叠：')
c = np.vstack((a,b))
print (c)


#hstack水平拼接

a = np.array([[1,2],[3,4]])
 
print ('第一个数组：')
print (a)
print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：')
print (b)
print ('\n')
 
print ('水平堆叠：')
c = np.hstack((a,b))
print (c)
print ('\n')

第一个数组：
[[1 2 3]
 [4 5 6]]


向数组添加元素：
[1 2 3 4 5 6 7 8 9]


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]
第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


竖直堆叠：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


水平堆叠：
[[1 2 5 6]
 [3 4 7 8]]




# 数组迭代

In [ ]:
import numpy as np

a = np.arange(6).reshape(2,3)
print(a[0, 2])

print(a.T)



In [4]:
# 在 sort 函数中排序字段 
dt = np.dtype([('name',  'S10'),('age',  int)]) 
a = np.array([("raju",21),("anil",25),("ravi",  17),  ("amar",27)], dtype = dt)  
print ('我们的数组是：')
print (a)
print ('\n')
print ('按 name 排序：')
print (np.sort(a, order =  'name'))

我们的数组是：
[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]


按 name 排序：
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


# 平展数组