# Test for my pandas

In [6]:
import pandas as pd
pd.__version__

mydataset = {
    "sites":["google", "cainiao", "wiki"],
    "number":[1, 2, 3]
}

my = pd.DataFrame(mydataset)
print(my)

print("---------")
a = [1, 2, 3]
myla = pd.Series(a)
print(myla)

import numpy as np
zero = np.zeros([4,8])
print(zero)

     sites  number
0   google       1
1  cainiao       2
2     wiki       3
---------
0    1
1    2
2    3
dtype: int64
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:
import pandas as pd
sites = {1: "Google", 2: "Runoob", 3: "Wiki"}

myvar = pd.Series(sites)

print(myvar)

print("-------------")
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

# 数据载入到 DataFrame 对象
df = pd.DataFrame(data)

print("df：")
print(df)
# 返回第一行
print(df.loc[0])
# 返回第二行
print(df.loc[1])

print(df.loc[0][1])

1    Google
2    Runoob
3      Wiki
dtype: object
-------------
df：
   calories  duration
0       420        50
1       380        40
2       390        45
calories    420
duration     50
Name: 0, dtype: int64
calories    380
duration     40
Name: 1, dtype: int64
50
